project:
  type: website
 # output-dir: docs

website:
  title: "Jasper Yang"
  description: "Jasper Yang's personal site"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/yangjasp
      - icon: twitter
        href: https://twitter.com/jyang29
      - text: CV
        href: JasperYangCV20251230.pdf
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

